### PR TITLE
Allow max int value on max liquidity check

### PR DESCRIPTION
**Pull request by hyunchel**
## Related Issue
Which issue does this pull request resolve? #370 
This PR replaces #368 

## Description of changes
This commit updates a tick spacing fuzz test to include maximum integer value of liquidity as a valid number.

### CODE REVIEW

**Comment by hensha256** [comment]
thank you for making this!

the test failures are from an unrelated fuzz edgecase that someone from the team is fixing in PR #503 thats about to be merged. Once thats in you can merge main and then we can merge this!

**Comment by hensha256** [comment]
ok that PR is merged!! if you can merge main here itll fix those failing tests and then i can approve 👯

**Comment by hyunchel** [comment]
Thank you for the quick turnaround! I'm still getting an error on `code coverage`. I can look into it if needed though it does not seem to be "required".

**Comment by hensha256** [comment]
thats just because your PR is from a fork that cannot access our github secrets :) no problem, we can merge anyway!

**Review by hensha256 — APPROVED** [review]

**Comment by hensha256** [comment]
merge when youre ready! thank you for your contribution!

**Comment by hensha256** [comment]
ahhh thats because coverage is failing 🤦 if all of CI passes you would be able to merge haha
no problem - i will merge it now!

**Pull request merged**
