### PR TITLE
Migrate SwapMath Test  to foundry

### PR DESCRIPTION
**Pull request by jobmwitah**
## Related Issue
Which issue does this pull request resolve?
This pull request migrates SwapMath tests from HardHat to Foundry (17 test cases), a part of https://github.com/Uniswap/v4-core/issues/315 .

## Description of changes

- Migrated 17 SwapMath tests to Foundry
- Removed hardhat implementations after migration

``` solidity
Running 17 tests for test/foundry-tests/SwapMath.t.sol:swapMathTest
[PASS] testAmountOutIsCappedAtTheDesiredAmountOut() (gas: 9355)
[PASS] testEntireInputAmountTakenAsFee() (gas: 9344)
[PASS] testExactAmountInThatGetsCappedAtPriceTargetInOneForZero() (gas: 9343)
[PASS] testExactAmountInThatIsFullySpentInOneForZero() (gas: 10322)
[PASS] testExactAmountOutThatGetsCappedAtPriceTargetInOneForZero() (gas: 9342)
[PASS] testExactAmountOutThatIsFullyReceivedInOneForZero() (gas: 10788)
[PASS] testHandlesIntermediateInsufficientLiquidityInOneForZeroExactOutputCase() (gas: 8654)
[PASS] testHandlesIntermediateInsufficientLiquidityInZeroForOneExactOutputCase() (gas: 8666)
[PASS] testSwapOneForZeroExactInCapped() (gas: 8235)
[PASS] testSwapOneForZeroExactInPartial() (gas: 9041)
[PASS] testSwapOneForZeroExactOutCapped() (gas: 7985)
[PASS] testSwapOneForZeroExactOutPartial() (gas: 9065)
[PASS] testSwapZeroForOneExactInCapped() (gas: 8204)
[PASS] testSwapZeroForOneExactInPartial() (gas: 9215)
[PASS] testSwapZeroForOneExactOutCapped() (gas: 8005)
[PASS] testSwapZeroForOneExactOutPartial() (gas: 9237)
[PASS] testTargetPriceOf1UsesPartialInputAmount() (gas: 8662)
Test result: ok. 17 passed; 0 failed; 0 skipped; finished in 7.87ms
```

### CODE REVIEW

**Review by Aryan9592 — APPROVED** [review]

**Comment by ewilz** [comment]
plz rename PR to be more specific to SwapMath

**Comment by ewilz** [comment]
Sorry for the late review.

can delete SwapMathTest contract and just use that library inside the new forge test contract. (was needed for js testing) can reference this PR: (https://github.com/Uniswap/v4-core/pull/320/files). Other things of note: must delete old snapshots and generate new forge ones. Then if you can move the SwapMath echnidna test to a fuzz test here, if not, feel free to give me write access and I'll do it. THe linked PR is a good resource for all the things that need to get done!

**Review by ewilz — CHANGES_REQUESTED** [review]
address previous comment!

**Comment by MwitahJob** [comment]
Sorry for late reply, I will work on it tomorrow

**Pull request closed without merging**
