### PR TITLE
Update Slot0.t.sol so that masks are inlined (Issue #797)

### PR DESCRIPTION
**Pull request by floor-licker**
In response to Issue #797, the bit masks are now inlined as opposed to being defined as constants.

Slot0.t.sol previously deviated from the standard of inline bit masks, by instead defining them as constants. I've updated the code so that they now conform to the standard that the other contracts adhere to, which is masks being defined inline.

Please feel free to respond to the pull request or reach out via my socials if there are any changes that need to be made.

### CODE REVIEW

**Comment by floor-licker** [comment]
Hey @vimageDE just wondering if you'd be able to take a look at this PR. Thanks!

**Comment by floor-licker** [comment]
Hey @hensha256 just wondering if you'd be able to take a look at this PR. Thanks!

**Comment by snreynolds** [comment]
hey! I think actually issue #797 was to make all places where we do any masks a constant so that they matched Slot0.sol file, and not actually worried about the test files.

**Comment by snreynolds** [comment]
Since the code is frozen now, we won't be making that change and I'll be closing the issue #797

**Comment by snreynolds** [comment]
Closing as 797 is no longer an issue

**Pull request closed without merging**
