### PR TITLE
Replace MockERC20 with solmate's MockERC20

### PR DESCRIPTION
**Pull request by saucepoint**
## Related Issue
When using `solmate's MockERC20` in a v4 repo, `wagmi` cannot generate types because of a naming collision with `v4-core's MockERC20`

Reproducible here: https://github.com/saucepoint/wagmi-uniswap-v4-bug

## Description of changes

* Replaced `test/foundry-tests/utils/MockERC20.sol` with `solmate/test/utils/mocks/MockERC20.sol`

### CODE REVIEW

**Comment by marktoda** [comment]
could we instead just use solmate/MockERC20?

**Comment by marktoda** [comment]
would be nice to unify around solmate impl imo

**Comment by marktoda** [comment]
and UniMockERC20 kinda ugly name :D

**Comment by hensha256** [comment]
LGTM! I can see not all your commits are signed 😢 please can you sign them all, and then I can approve?

**Review by marktoda — APPROVED** [review]

**Review by marktoda — APPROVED** [review]

**Pull request merged**
