### PR TITLE
Allow max int value on max liquidity check

### PR DESCRIPTION
**Pull request by hyunchel**
## Related Issue
#370 

## Description of changes
This commit updates a tick spacing fuzz test to include maximum integer value of liquidity as a valid number. Without this change, the fuzz test will fail when the tick spacing is set to the maximum tick value.

### CODE REVIEW

**Comment by hyunchel** [comment]
Updated comments to tag the related issue.

**Review by aadams — DISMISSED** [review]
nice catch

this is also checked (correctly) in Pool.t.sol

**Comment by hyunchel** [comment]
Thanks for the review! I've updated this branch to the latest main.
Please let me know if you need any more action from my end.

**Review by aadams — APPROVED** [review]

**Comment by hensha256** [comment]
Hey! Thanks for your PR. Would you mind signing your first commit (its not verified). Then once youve merged in main we can approve and merge!

**Comment by hyunchel** [comment]
Well I mishandled this situation.
I ran the following command before realizing that this signs all commits starting after the commit I should've signed:

```
git rebase --exec 'git ci --amend --no-edit -n -S' -i 1231234a
```
I'm not sure how to abort this since I have force-pushed. I need a guidance, if available.

Should I close this PR and open a new one with fresh new commit that fixes the same issue?

**Comment by hensha256** [comment]
Hey @hyunchel ! Sorry for the delay here.
Yes I think its best now to just close this pull request, and open a new one from a fresh branch off main!

**Comment by hensha256** [comment]
Just bumping this @hyunchel

**Comment by hensha256** [comment]
Hey! Just to let you know if we dont get a response int he next few days we will fix this ourselves. However we would love to be able to have you commit this to show your rightful contributions to V4!

**Comment by hyunchel** [comment]
I apologize for the delayed response! I'll replace this with another PR today. Thank you for your the patience and the kind warning.

**Pull request closed without merging**
