### PR TITLE
Remove PoolGetters

### PR DESCRIPTION
**Pull request by havi-kim**
## Related Issue
Which issue does this pull request resolve?
#680 

## Description of changes
- Removed PoolGetters.
- The replacement of PoolGetters with extsload equivalents is already implemented in StateLibrary (see #579).

### CODE REVIEW

**Review by snreynolds — APPROVED** [review]
thanks!

**Comment by hensha256** [comment]
hey @havi-kim ! please can you sign your commit? we cannot merge any un-signed commits

**Comment by hensha256** [comment]
hey @havi-kim ! its still not signed 😞 youll know its signed when it says `verified` next to the commit hash.   See [this PR](https://github.com/Uniswap/v4-core/pull/677) as an example.

Screenshot 2024-05-22 at 09 50 43

**Comment by havi-kim** [comment]
@hensha256 
Thank you so much for your kind explanation.
I've signed it. Could you please check if it's`verified`?

**Review by hensha256 — APPROVED** [review]

**Pull request merged**
