### PR TITLE
chore: fix shadowed var name

### PR DESCRIPTION
**Pull request by devtooligan**
## Related Issue
The parameter `owner` in `PoolManager.getLiquidity` shadows an existing state variable.

Per the contribution guidelines:

> 2. These contracts follow the [solidity style guide](https://docs.soliditylang.org/en/v0.8.17/style-guide.html) with one minor exception of using the _prependUnderscore style naming for internal contract functions, internal top-level parameters, and function parameters with naming collisions.

## Description of changes

Prepends a `_` to the offending parameter name.

### CODE REVIEW

**Review by marktoda — APPROVED** [review]
nice thank you! semi OCD want them to either all have underscores or none but think its fine

**Comment by marktoda** [comment]
maybe another name would make more sense here then - `holder`?

**Comment by devtooligan** [comment]
I'm with you, @marktoda .  Tbh there's really no perfect system for using _.  

Changed to `holder`, I like it,  no more _

**Comment by hensha256** [comment]
The diff is 0 lines on this PR 😆 I think it had already been fixed on main, and when you merged it in your PR became 0.

You're welcome to change it to `holder` if thats better - otherwise we can close this.

**Comment by hensha256** [comment]
Closing :)

**Pull request closed without merging**
