### PR TITLE
Fix shadowed state var

### PR DESCRIPTION
**Pull request by kadenzipfel**
## Description of changes

Fixes shadowed state variable `owner` in `getPosition` by adding an underscore to the param as was done in `getLiquidity`

### CODE REVIEW

**Comment by zhongeric** [comment]
Hi! Thanks for the contribution, can you update your branch with the latest main?

**Review by snreynolds — APPROVED** [review]

**Comment by kadenzipfel** [comment]
> Hi! Thanks for the contribution, can you update your branch with the latest main?

done :)

**Comment by zhongeric** [comment]
Oops can you go back and sign your commits?

**Comment by snreynolds** [comment]
thanks for the change - happy to get it merged can you just update to latest main?

**Pull request closed without merging**
