### PR TITLE
Add sparse extsload

### PR DESCRIPTION
**Pull request by Philogy**
## Related Issue
#624

## Description of changes
Add an optimized implementation for a function that takes an array of storage keys, loads their values from storage and returns them.

### CODE REVIEW

**Review by saucepoint — CHANGES_REQUESTED** [review]
can you add the new function signature to `IExtsload` so its available through `IPoolManager`

**Comment by Philogy** [comment]
@saucepoint done

**Comment by hensha256** [comment]
Please can you run `forge test --isolate` ? bytecode size has increased here but missing the snapshot for it

**Comment by Philogy** [comment]
Updated the gas snapshot @hensha256

**Review by gretzke — APPROVED** [review]

**Pull request merged**
