### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by xiaolou86**

### CODE REVIEW

**Comment by hensha256** [comment]
Please can you sign your commit? :)

**Comment by xiaolou86** [comment]
@hensha256 Thanks for your review. I signed commit just now.

**Review by zhongeric — DISMISSED** [review]

**Comment by snreynolds** [comment]
Update w/main but lgtm

**Comment by xiaolou86** [comment]
@hensha256 @zhongeric @snreynolds Thanks for all your review. I have updated since the change of standard foundry directory structure.

**Review by zhongeric — APPROVED** [review]

**Comment by zhongeric** [comment]
Thank you for the contribution! I've went ahead and merged it for now to avoid any possible future merge conflicts :)

**Comment by xiaolou86** [comment]
@zhongeric Thank you very much!

**Pull request merged**
