### PR TITLE
Import and modify `BitMath` implementation from `Solady`

### PR DESCRIPTION
**Pull request by shuhuiluo**
## Related Issue
Which issue does this pull request resolve?

## Description of changes

`BitMath` is optimized heavily by importing and modifying `mostSignificantBit` and `leastSignificantBit` implementations from [Solady::LibBit](https://github.com/Vectorized/solady/blob/37b4fd04dd82977eb0161839389187abb7afdb58/src/utils/LibBit.sol) which uses the De Bruijn lookup.

### CODE REVIEW

**Review by hensha256 — CHANGES_REQUESTED** [review]
Thanks for the PR! Please could you insert some comments to explain what each chunk of the assembly does? With assembly its even more important to explain code clearly :)

**Comment by shuhuiluo** [comment]
> Thanks for the PR! Please could you insert some comments to explain what each chunk of the assembly does? With assembly its even more important to explain code clearly :)

Added. Comments were kept at a minimal since the original code wasn't annotated.

**Comment by snreynolds** [comment]
Hi - could you also update this one to main as well? Want to get updated gas estimates! Thanks!

**Comment by shuhuiluo** [comment]
Closing because of #785.

**Pull request closed without merging**
